rules:
  property-sort-order:
    - 1
    - order: recess
  no-color-literals: 0
  single-line-per-selector: 0
  empty-line-between-blocks: 0
  no-color-keywords: 0
  class-name-format:
    - 1
    - convention: camelcase
  variable-name-format:
    - 1
    - convention: camelcase
